# Generated by Django 3.1.5 on 2021-03-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('author', 'author')]},
        ),
    ]
