# Generated by Django 3.1.5 on 2021-03-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210306_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon_url',
            field=models.URLField(default='000', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
