# Generated by Django 3.1.5 on 2021-03-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210306_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
