# Generated by Django 3.1.5 on 2021-03-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210306_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updates', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.ForeignKey(default='111', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.notification'),
            preserve_default=False,
        ),
    ]
